// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCODz3N7KjKFQfYJ8A-P9kbcKSImwKj658',
    appId: '1:735700651958:android:ee809f835fdcbff60bbb17',
    messagingSenderId: '735700651958',
    projectId: 'hotelia-dfd85',
    databaseURL: 'https://hotelia-dfd85-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hotelia-dfd85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHoFyq8g1wPRhRNhx91bTR1lnBe1qjR9c',
    appId: '1:735700651958:ios:d3c41c0f97e95f8a0bbb17',
    messagingSenderId: '735700651958',
    projectId: 'hotelia-dfd85',
    databaseURL: 'https://hotelia-dfd85-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hotelia-dfd85.appspot.com',
    iosClientId: '735700651958-jkqc044i3ekv9irudjelv9k8rhf7ma51.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelia',
  );
}
